[package]
name = "csrf"
version = "0.2.6"
authors = [ "heartsucker <heartsucker@autistici.org>" ]
description = "CSRF protection primitives"
homepage = "https://github.com/heartsucker/rust-csrf"
repository = "https://github.com/heartsucker/rust-csrf"
documentation = "https://docs.rs/csrf"
readme = "README.md"
license = "MIT"
keywords = [ "csrf", "web", "security", "http" ]
categories = [ "web-programming", "authentication", "cryptography" ]

[badges]
travis-ci = { repository = "heartsucker/rust-csrf", branch = "master" }
appveyor = { repository = "heartsucker/rust-csrf", branch = "master", service = "github" }

[lib]
name = "csrf"
path = "./src/lib.rs"

[features]
iron = [ "typemap" ]

[dependencies]
data-encoding = "2.0.0-rc.1"
log = "0.3"
ring = "0.11"
rust-crypto = "0.2"
time = "0.1"
typemap = { version = "0.3", optional = true }
