[package]
name = "csrf"
version = "0.1.0"
authors = [ "heartsucker <heartsucker@autistici.org>" ]
description = "CSRF protection primitives"
homepage = "https://github.com/heartsucker/rust-csrf"
repository = "https://github.com/heartsucker/rust-csrf"
documentation = "https://docs.rs/csrf"
readme = "README.md"
license = "MIT"
keywords = [ "csrf", "web", "security", "http" ]
categories = [ "web-programming::http-server", "authentication", "cryptography" ]

[badges]
travis-ci = { repository = "heartsucker/rust-csrf", branch = "develop" }

[lib]
name = "csrf"
path = "./src/lib.rs"

[features]
iron = [ "typemap" ]

[dependencies]
log = "0.3"
ring = "0.7"
rust-crypto = "0.2"
rustc-serialize = "0.3"
time = "0.1"
typemap = { version = "0.3", optional = true }
